# Dockerfile generated by deploy.py
# Pinned to Python 3.11 to ensure prebuilt wheels for numpy/scikit-learn and avoid Cython builds.
FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1

WORKDIR /app

# System deps: build tools + libpq for psycopg2 (binary wheel usually suffices, but safe to have headers)
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

# Install Python deps
COPY requirements.txt /app/requirements.txt
RUN python -m pip install --upgrade pip setuptools wheel \
    && pip install -r requirements.txt

# App source
COPY . /app

# Render/Cloud Run provide PORT; default to 8080
ENV PORT=8080

# Gunicorn is recommended for prod; app entrypoint is app:app
CMD gunicorn --bind 0.0.0.0:${PORT} --workers 4 --timeout 120 app:app